version: "3.4"

services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=school
      - POSTGRES_PASSWORD=school
      - POSTGRES_DB=school
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    depends_on:
      - db
    env_file:
      - .env

  tailwind:
    build:
      context: .
      target: frontend-build
    volumes:
      - ./:/app/
    tty: true

volumes:
  postgres_data:
