[tool.isort]
profile = "black"

[tool.bumpver]
current_version = "2023.4"
version_pattern = "YYYY.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
]
"schools/__init__.py" = [
    'VERSION = "{version}"',
]

